#!/usr/bin/python3

import sys
import subprocess


TAG = "4.58.1-1"


def run(cmd):
	print(f"+ {cmd}")
	return subprocess.call(cmd, shell=True)


def main():
	return run(f"docker run --rm --net=host -v mfsmaster_data:/var/lib/mfs --name mfsmaster docker.io/rpodgorny/moosefs:{TAG} ./mfsmaster.sh")


if __name__ == "__main__":
	sys.exit(main())
