#!/usr/bin/python3

import sys
import subprocess


def run(cmd):
	print('+ %s' % cmd)
	return subprocess.call(cmd, shell=True)


def main():
	return run('docker run --rm --net=host --name mfscgiserv docker.io/rpodgorny/moosefs:4.57.6-1 ./mfscgiserv.sh')


if __name__ == '__main__':
	sys.exit(main())
